server:
  port: 8888
spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tangchengzao/config-repo
          search-paths: licensingservice, organizationservice
#        native:
#          search-locations: classpath:config/licensingservice

